#application.yaml
spring:
  application:
    name: demo
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ecoTrack
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
supabase:
  url: ${SUPABASE_URL}
  key: ${SUPABASE_SECRET}
  bucket: ecoTrackImages
keycloak:
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL}
  realm: springboot-test
  resource: ${ADMIN_ID}
  credentials:
    secret: ${ADMIN_SECRET}
  ssl-required: external
  use-resource-role-mappings: true
  bearer-only: false
  public-client: false
  confidential-port: 0
huggingface:
  api:
    key: ${HUGGIN_FACE_KEY}
grok:
  api:
    key: ${GROK_API_KEY}
osrm:
  url: ${OSRM_URL}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.security.oauth2.jwt: DEBUG
server:
  port: ${PORT:8080}
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false
app:
  cors:
    allowed-origins: ${FRONTEND_URL}
management:
  endpoint:
    health:
      show-details: when-authorized
  endpoints:
    web:
      exposure:
        include: health
  health:
    defaults:
      enabled: true
