spring:
  application:
    name: demo
  data:
    mongodb:
      uri: mongodb+srv://elaa:EiyAyh3vA98hib@cluster0.vg9stxe.mongodb.net/ecoTrack?retryWrites=true&w=majority
      database: ecoTrack
server:
  port: 8080
